### ISSUE TITLE
Using bash script with AppRun seg faults

### ISSUE THREAD

**Issue by mmtrt** [AppImageCrafters/AppRun#22]
But running that appimage under archlinux errors that it can't find bash, dirname, cat, some other commands used in bash script,

so adding path /bin /usr/bin in starting of script fixes appimage exec but then same appimg seg faults on ubuntu.

**Comment by azubieta** [comment]
To run any kind of script from your AppImage you have to bundle the script interpreter. In case of bash you need to bundle batch itself. Use the script interpreter as entry point and pass the script as the first argument the the rest of your arguments. 

It would be something like this:
```
AppDir:
  app_info:
     exec: bin/bash
     exec_args: $APPDIR/my_cool_script.sh $@
```
