### ISSUE TITLE
Unable to execute binaries with sudo inside AppImage

### ISSUE THREAD

**Issue by spvkgn** [AppImageCrafters/AppRun#64]
Use this simple `AppImageBuilder.yml` to build the AppImage with `appimage-builder`:
```yaml
version: 1

AppDir:
  path: ./AppDir

  app_info:
    id: org.gnu.bash
    name: bash
    icon: utilities-terminal
    version: 5.0.16
    exec: bin/bash
    exec_args: $@

  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse'
        
    include:
      - bash
      - coreutils
    exclude:
      - libpcre3

AppImage:
  arch: x86_64
  comp: gzip
```
Check the AppImage is working - OK:
```
$ ./bash-5.0.16-x86_64.AppImage --version | head -n1
GNU bash, версия 5.0.16(1)-release (x86_64-pc-linux-gnu)
```
Run the AppImage and execute any binary inside AppImage - OK:
```
$ $APPDIR/usr/bin/head -n1 /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```
Execute any binary inside AppImage with `sudo`, for instance, reading `/etc/sudoers` contents - it fails with error "command not found":
```
$ $APPDIR/usr/bin/head -n1 /etc/sudoers
/tmp/.mount_bash-582FuSk/usr/bin/head: cannot open '/etc/sudoers' for reading: Permission denied

$ sudo $APPDIR/usr/bin/head -n1 /etc/sudoers
[sudo] password for pavel: 
sudo: /tmp/.mount_bash-582FuSk/usr/bin/head: command not found
```
